// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace chirp {

class ServiceLayer final {
 public:
  static constexpr char const* service_full_name() {
    return "chirp.ServiceLayer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status registeruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::chirp::RegisterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::RegisterReply>> Asyncregisteruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::RegisterReply>>(AsyncregisteruserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::RegisterReply>> PrepareAsyncregisteruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::RegisterReply>>(PrepareAsyncregisteruserRaw(context, request, cq));
    }
    virtual ::grpc::Status chirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::chirp::ChirpReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ChirpReply>> Asyncchirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ChirpReply>>(AsyncchirpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ChirpReply>> PrepareAsyncchirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ChirpReply>>(PrepareAsyncchirpRaw(context, request, cq));
    }
    virtual ::grpc::Status follow(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::chirp::FollowReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::FollowReply>> Asyncfollow(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::FollowReply>>(AsyncfollowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::FollowReply>> PrepareAsyncfollow(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::FollowReply>>(PrepareAsyncfollowRaw(context, request, cq));
    }
    virtual ::grpc::Status read(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::chirp::ReadReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ReadReply>> Asyncread(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ReadReply>>(AsyncreadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ReadReply>> PrepareAsyncread(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ReadReply>>(PrepareAsyncreadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::chirp::MonitorReply>> monitor(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::chirp::MonitorReply>>(monitorRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::MonitorReply>> Asyncmonitor(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::MonitorReply>>(AsyncmonitorRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::MonitorReply>> PrepareAsyncmonitor(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::MonitorReply>>(PrepareAsyncmonitorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::chirp::StreamReply>> stream(::grpc::ClientContext* context, const ::chirp::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::chirp::StreamReply>>(streamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::StreamReply>> Asyncstream(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::StreamReply>>(AsyncstreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::StreamReply>> PrepareAsyncstream(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chirp::StreamReply>>(PrepareAsyncstreamRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void registeruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void chirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void follow(::grpc::ClientContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void read(::grpc::ClientContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void monitor(::grpc::ClientContext* context, ::chirp::MonitorRequest* request, ::grpc::experimental::ClientReadReactor< ::chirp::MonitorReply>* reactor) = 0;
      virtual void stream(::grpc::ClientContext* context, ::chirp::StreamRequest* request, ::grpc::experimental::ClientReadReactor< ::chirp::StreamReply>* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::RegisterReply>* AsyncregisteruserRaw(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::RegisterReply>* PrepareAsyncregisteruserRaw(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ChirpReply>* AsyncchirpRaw(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ChirpReply>* PrepareAsyncchirpRaw(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::FollowReply>* AsyncfollowRaw(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::FollowReply>* PrepareAsyncfollowRaw(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ReadReply>* AsyncreadRaw(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chirp::ReadReply>* PrepareAsyncreadRaw(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::chirp::MonitorReply>* monitorRaw(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chirp::MonitorReply>* AsyncmonitorRaw(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chirp::MonitorReply>* PrepareAsyncmonitorRaw(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::chirp::StreamReply>* streamRaw(::grpc::ClientContext* context, const ::chirp::StreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chirp::StreamReply>* AsyncstreamRaw(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chirp::StreamReply>* PrepareAsyncstreamRaw(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status registeruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::chirp::RegisterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::RegisterReply>> Asyncregisteruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::RegisterReply>>(AsyncregisteruserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::RegisterReply>> PrepareAsyncregisteruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::RegisterReply>>(PrepareAsyncregisteruserRaw(context, request, cq));
    }
    ::grpc::Status chirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::chirp::ChirpReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ChirpReply>> Asyncchirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ChirpReply>>(AsyncchirpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ChirpReply>> PrepareAsyncchirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ChirpReply>>(PrepareAsyncchirpRaw(context, request, cq));
    }
    ::grpc::Status follow(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::chirp::FollowReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::FollowReply>> Asyncfollow(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::FollowReply>>(AsyncfollowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::FollowReply>> PrepareAsyncfollow(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::FollowReply>>(PrepareAsyncfollowRaw(context, request, cq));
    }
    ::grpc::Status read(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::chirp::ReadReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ReadReply>> Asyncread(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ReadReply>>(AsyncreadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ReadReply>> PrepareAsyncread(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chirp::ReadReply>>(PrepareAsyncreadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::chirp::MonitorReply>> monitor(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::chirp::MonitorReply>>(monitorRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::MonitorReply>> Asyncmonitor(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::MonitorReply>>(AsyncmonitorRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::MonitorReply>> PrepareAsyncmonitor(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::MonitorReply>>(PrepareAsyncmonitorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::chirp::StreamReply>> stream(::grpc::ClientContext* context, const ::chirp::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::chirp::StreamReply>>(streamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::StreamReply>> Asyncstream(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::StreamReply>>(AsyncstreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::StreamReply>> PrepareAsyncstream(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chirp::StreamReply>>(PrepareAsyncstreamRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void registeruser(::grpc::ClientContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response, std::function<void(::grpc::Status)>) override;
      void chirp(::grpc::ClientContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response, std::function<void(::grpc::Status)>) override;
      void follow(::grpc::ClientContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response, std::function<void(::grpc::Status)>) override;
      void read(::grpc::ClientContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response, std::function<void(::grpc::Status)>) override;
      void monitor(::grpc::ClientContext* context, ::chirp::MonitorRequest* request, ::grpc::experimental::ClientReadReactor< ::chirp::MonitorReply>* reactor) override;
      void stream(::grpc::ClientContext* context, ::chirp::StreamRequest* request, ::grpc::experimental::ClientReadReactor< ::chirp::StreamReply>* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::chirp::RegisterReply>* AsyncregisteruserRaw(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chirp::RegisterReply>* PrepareAsyncregisteruserRaw(::grpc::ClientContext* context, const ::chirp::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chirp::ChirpReply>* AsyncchirpRaw(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chirp::ChirpReply>* PrepareAsyncchirpRaw(::grpc::ClientContext* context, const ::chirp::ChirpRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chirp::FollowReply>* AsyncfollowRaw(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chirp::FollowReply>* PrepareAsyncfollowRaw(::grpc::ClientContext* context, const ::chirp::FollowRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chirp::ReadReply>* AsyncreadRaw(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chirp::ReadReply>* PrepareAsyncreadRaw(::grpc::ClientContext* context, const ::chirp::ReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::chirp::MonitorReply>* monitorRaw(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request) override;
    ::grpc::ClientAsyncReader< ::chirp::MonitorReply>* AsyncmonitorRaw(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::chirp::MonitorReply>* PrepareAsyncmonitorRaw(::grpc::ClientContext* context, const ::chirp::MonitorRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::chirp::StreamReply>* streamRaw(::grpc::ClientContext* context, const ::chirp::StreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::chirp::StreamReply>* AsyncstreamRaw(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::chirp::StreamReply>* PrepareAsyncstreamRaw(::grpc::ClientContext* context, const ::chirp::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_registeruser_;
    const ::grpc::internal::RpcMethod rpcmethod_chirp_;
    const ::grpc::internal::RpcMethod rpcmethod_follow_;
    const ::grpc::internal::RpcMethod rpcmethod_read_;
    const ::grpc::internal::RpcMethod rpcmethod_monitor_;
    const ::grpc::internal::RpcMethod rpcmethod_stream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response);
    virtual ::grpc::Status chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response);
    virtual ::grpc::Status follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response);
    virtual ::grpc::Status read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response);
    virtual ::grpc::Status monitor(::grpc::ServerContext* context, const ::chirp::MonitorRequest* request, ::grpc::ServerWriter< ::chirp::MonitorReply>* writer);
    virtual ::grpc::Status stream(::grpc::ServerContext* context, const ::chirp::StreamRequest* request, ::grpc::ServerWriter< ::chirp::StreamReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_registeruser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_registeruser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_registeruser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestregisteruser(::grpc::ServerContext* context, ::chirp::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::chirp::RegisterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_chirp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_chirp() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_chirp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestchirp(::grpc::ServerContext* context, ::chirp::ChirpRequest* request, ::grpc::ServerAsyncResponseWriter< ::chirp::ChirpReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_follow() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfollow(::grpc::ServerContext* context, ::chirp::FollowRequest* request, ::grpc::ServerAsyncResponseWriter< ::chirp::FollowReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_read() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestread(::grpc::ServerContext* context, ::chirp::ReadRequest* request, ::grpc::ServerAsyncResponseWriter< ::chirp::ReadReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_monitor() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status monitor(::grpc::ServerContext* context, const ::chirp::MonitorRequest* request, ::grpc::ServerWriter< ::chirp::MonitorReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmonitor(::grpc::ServerContext* context, ::chirp::MonitorRequest* request, ::grpc::ServerAsyncWriter< ::chirp::MonitorReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(4, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_stream() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream(::grpc::ServerContext* context, const ::chirp::StreamRequest* request, ::grpc::ServerWriter< ::chirp::StreamReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststream(::grpc::ServerContext* context, ::chirp::StreamRequest* request, ::grpc::ServerAsyncWriter< ::chirp::StreamReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(5, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_registeruser<WithAsyncMethod_chirp<WithAsyncMethod_follow<WithAsyncMethod_read<WithAsyncMethod_monitor<WithAsyncMethod_stream<Service > > > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_registeruser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_registeruser() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::chirp::RegisterRequest, ::chirp::RegisterReply>(
          [this](::grpc::ServerContext* context,
                 const ::chirp::RegisterRequest* request,
                 ::chirp::RegisterReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->registeruser(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_registeruser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_chirp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_chirp() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::chirp::ChirpRequest, ::chirp::ChirpReply>(
          [this](::grpc::ServerContext* context,
                 const ::chirp::ChirpRequest* request,
                 ::chirp::ChirpReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->chirp(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_chirp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_follow() {
      ::grpc::Service::experimental().MarkMethodCallback(2,
        new ::grpc::internal::CallbackUnaryHandler< ::chirp::FollowRequest, ::chirp::FollowReply>(
          [this](::grpc::ServerContext* context,
                 const ::chirp::FollowRequest* request,
                 ::chirp::FollowReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->follow(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_read() {
      ::grpc::Service::experimental().MarkMethodCallback(3,
        new ::grpc::internal::CallbackUnaryHandler< ::chirp::ReadRequest, ::chirp::ReadReply>(
          [this](::grpc::ServerContext* context,
                 const ::chirp::ReadRequest* request,
                 ::chirp::ReadReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->read(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_monitor() {
      ::grpc::Service::experimental().MarkMethodCallback(4,
        new ::grpc::internal::CallbackServerStreamingHandler< ::chirp::MonitorRequest, ::chirp::MonitorReply>(
          [this] { return this->monitor(); }));
    }
    ~ExperimentalWithCallbackMethod_monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status monitor(::grpc::ServerContext* context, const ::chirp::MonitorRequest* request, ::grpc::ServerWriter< ::chirp::MonitorReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerWriteReactor< ::chirp::MonitorRequest, ::chirp::MonitorReply>* monitor() {
      return new ::grpc::internal::UnimplementedWriteReactor<
        ::chirp::MonitorRequest, ::chirp::MonitorReply>;}
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_stream() {
      ::grpc::Service::experimental().MarkMethodCallback(5,
        new ::grpc::internal::CallbackServerStreamingHandler< ::chirp::StreamRequest, ::chirp::StreamReply>(
          [this] { return this->stream(); }));
    }
    ~ExperimentalWithCallbackMethod_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream(::grpc::ServerContext* context, const ::chirp::StreamRequest* request, ::grpc::ServerWriter< ::chirp::StreamReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerWriteReactor< ::chirp::StreamRequest, ::chirp::StreamReply>* stream() {
      return new ::grpc::internal::UnimplementedWriteReactor<
        ::chirp::StreamRequest, ::chirp::StreamReply>;}
  };
  typedef ExperimentalWithCallbackMethod_registeruser<ExperimentalWithCallbackMethod_chirp<ExperimentalWithCallbackMethod_follow<ExperimentalWithCallbackMethod_read<ExperimentalWithCallbackMethod_monitor<ExperimentalWithCallbackMethod_stream<Service > > > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_registeruser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_registeruser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_registeruser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_chirp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_chirp() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_chirp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_follow() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_read() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_monitor() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status monitor(::grpc::ServerContext* context, const ::chirp::MonitorRequest* request, ::grpc::ServerWriter< ::chirp::MonitorReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_stream() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream(::grpc::ServerContext* context, const ::chirp::StreamRequest* request, ::grpc::ServerWriter< ::chirp::StreamReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_registeruser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_registeruser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_registeruser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestregisteruser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_chirp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_chirp() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_chirp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestchirp(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_follow() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfollow(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_read() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestread(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_monitor() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status monitor(::grpc::ServerContext* context, const ::chirp::MonitorRequest* request, ::grpc::ServerWriter< ::chirp::MonitorReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmonitor(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(4, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_stream() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream(::grpc::ServerContext* context, const ::chirp::StreamRequest* request, ::grpc::ServerWriter< ::chirp::StreamReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(5, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_registeruser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_registeruser() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->registeruser(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_registeruser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void registeruser(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_chirp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_chirp() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->chirp(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_chirp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void chirp(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_follow() {
      ::grpc::Service::experimental().MarkMethodRawCallback(2,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->follow(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void follow(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_read() {
      ::grpc::Service::experimental().MarkMethodRawCallback(3,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->read(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void read(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_monitor() {
      ::grpc::Service::experimental().MarkMethodRawCallback(4,
        new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->monitor(); }));
    }
    ~ExperimentalWithRawCallbackMethod_monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status monitor(::grpc::ServerContext* context, const ::chirp::MonitorRequest* request, ::grpc::ServerWriter< ::chirp::MonitorReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* monitor() {
      return new ::grpc::internal::UnimplementedWriteReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_stream() {
      ::grpc::Service::experimental().MarkMethodRawCallback(5,
        new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->stream(); }));
    }
    ~ExperimentalWithRawCallbackMethod_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream(::grpc::ServerContext* context, const ::chirp::StreamRequest* request, ::grpc::ServerWriter< ::chirp::StreamReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream() {
      return new ::grpc::internal::UnimplementedWriteReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_registeruser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_registeruser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::chirp::RegisterRequest, ::chirp::RegisterReply>(std::bind(&WithStreamedUnaryMethod_registeruser<BaseClass>::Streamedregisteruser, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_registeruser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status registeruser(::grpc::ServerContext* context, const ::chirp::RegisterRequest* request, ::chirp::RegisterReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedregisteruser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chirp::RegisterRequest,::chirp::RegisterReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_chirp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_chirp() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::chirp::ChirpRequest, ::chirp::ChirpReply>(std::bind(&WithStreamedUnaryMethod_chirp<BaseClass>::Streamedchirp, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_chirp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status chirp(::grpc::ServerContext* context, const ::chirp::ChirpRequest* request, ::chirp::ChirpReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedchirp(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chirp::ChirpRequest,::chirp::ChirpReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_follow() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::chirp::FollowRequest, ::chirp::FollowReply>(std::bind(&WithStreamedUnaryMethod_follow<BaseClass>::Streamedfollow, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::chirp::FollowRequest* request, ::chirp::FollowReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedfollow(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chirp::FollowRequest,::chirp::FollowReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_read() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< ::chirp::ReadRequest, ::chirp::ReadReply>(std::bind(&WithStreamedUnaryMethod_read<BaseClass>::Streamedread, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status read(::grpc::ServerContext* context, const ::chirp::ReadRequest* request, ::chirp::ReadReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedread(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chirp::ReadRequest,::chirp::ReadReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_registeruser<WithStreamedUnaryMethod_chirp<WithStreamedUnaryMethod_follow<WithStreamedUnaryMethod_read<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_monitor() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::SplitServerStreamingHandler< ::chirp::MonitorRequest, ::chirp::MonitorReply>(std::bind(&WithSplitStreamingMethod_monitor<BaseClass>::Streamedmonitor, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status monitor(::grpc::ServerContext* context, const ::chirp::MonitorRequest* request, ::grpc::ServerWriter< ::chirp::MonitorReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedmonitor(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::chirp::MonitorRequest,::chirp::MonitorReply>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_stream() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::SplitServerStreamingHandler< ::chirp::StreamRequest, ::chirp::StreamReply>(std::bind(&WithSplitStreamingMethod_stream<BaseClass>::Streamedstream, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status stream(::grpc::ServerContext* context, const ::chirp::StreamRequest* request, ::grpc::ServerWriter< ::chirp::StreamReply>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedstream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::chirp::StreamRequest,::chirp::StreamReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_monitor<WithSplitStreamingMethod_stream<Service > > SplitStreamedService;
  typedef WithStreamedUnaryMethod_registeruser<WithStreamedUnaryMethod_chirp<WithStreamedUnaryMethod_follow<WithStreamedUnaryMethod_read<WithSplitStreamingMethod_monitor<WithSplitStreamingMethod_stream<Service > > > > > > StreamedService;
};

}  // namespace chirp


#endif  // GRPC_service_2eproto__INCLUDED
